sudo: required
language: python

# which python versions to test
python:
  - "3.5"
  - "3.6"

# Cache directory $HOME/.cache/pip
cache: pip

# command before installation: install all dependencies and run CMAKE config
before_install:
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt
  - python -m pip uninstall -y sympde
  - wget https://raw.githubusercontent.com/pyccel/sympde/master/requirements.txt -O requirements_sympde.txt
  - python -m pip install -r requirements_sympde.txt
  - python -m pip install git+https://github.com/pyccel/sympde@master

# command to install project
install:
  - python -m pip install .

# command to run tests
script:
  - python -m pytest gelato 
